name: Build and push Helm chart

on:
  push:
    branches: [ master ]

jobs:
  #lint:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: Checkout
  #      uses: actions/checkout@v2
  #    - name: Fetch history
  #      run: git fetch --prune --unshallow
      #- name: Run testing TODO
      #  uses: helm/chart-testing-action@v1.0.0
      #  with:
      #    command: lint
  package:
    runs-on: ubuntu-latest
    #needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Package chart
        run: helm package .
      - name: Install helm push plugin
        run: helm plugin install https://github.com/chartmuseum/helm-push.git
      - name: Push chart
        env:
          URL: https://harbor.lhaidacher.com/chartrepo/onlineshop
          NAME: ${{ secrets.HARBOR_USERNAME }}
          PW: ${{ secrets.HARBOR_PASSWORD }}
        run: helm push search-service-chart-* ${{ env.URL }} -u ${{ env.NAME }} -p ${{ env.PW }}
